### ISSUE TITLE
Add target_include_directories in CMakeLists.txt 

### ISSUE THREAD

**Issue by umbreensabirmain** [rschoene/libfreqgen#3]
To enable to use the interface header `freq_gen.h` by other projects, please add the following in CMakeLists.txt.

```
target_include_directories(freqgen INTERFACE
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>)
```
after ` add_library(freqgen SHARED ${SOURCES})`

**Comment by rschoene** [comment]
Fixed in b4ebd33044cd1e6951f2ccda35ecce5df4455795
